### ISSUE TITLE
Working with a modified dataset

### ISSUE THREAD

**Issue by mikeyEcology** [FabiTheGabi/VideoProcessMining#1]
Hi @FabiTheGabi , 
Thank you for creating this software. It looks like it will be really useful for a lot of users of SlowFast. I have a couple of questions, as my dataset is slightly different, so I'm not sure it will work.
I have data similar to the AVA dataset, but not exactly. For each video, I have bounding box coordinates for each frame, and a label for the box. So essentially I have one csv (that can be split to train, val) that contains image (frame) name, label, bb coordinates. I don't have data for all of the csv's that are typically listed in AVA. 
My other difference is that I need to use every frame, not every second, because the object I'm trying to ID moves very fast and is sometimes only in the video for 1 second or less.
Do you think I can modify your scripts to make this work, or is it better to start from scratch?
Thank you!

**Comment by FabiTheGabi** [comment]
Hi @mikeyEcology,
thank you a lot for your feedback.

In my opinion, you have 2 choices.

Frist, you could write your own data loader, which allows frame-wise training. In this case, you can build on existing functionality, but you basically have to start from scratch.

Second, you could also transform your custom dataset into the AVA format. This should definetly work as well. The prototype is only able to train second-wise. Thus, you could transfrom your frame-wise annotations into second-wise annotations based on your videos' fps. I did the same for my custom dataset and only included lables that occured at full-second intervals. If you are able to transform your annotations and create the files as described in [Step 3 of Data Preparation](https://github.com/FabiTheGabi/VideoProcessMining/blob/master/slowfast/datasets/DATASET.md#step-3-prepare-initial-annotation-files-manually), the protoype facilitates creating some of the other required files automatically. I would suggest to give this option a try. Be aware that you drastically reduce your training data, if you train second-wise instead of frame-wise. 

Best regards :)

PS: I attatched some pseudo-code that I used to transfrom the data. Hopefully this gives you some insights :)
[frame_wise_to_second_wise.txt](https://github.com/FabiTheGabi/VideoProcessMining/files/5675892/frame_wise_to_second_wise.txt)

**Comment by mikeyEcology** [comment]
Thank you for your suggestions. I've actually been working on doing something similar to your second option. But I need every frame, because what I'm looking for moves very fast, so I'm essentially breaking down the video into frames (20 frames per second) and then creating videos where each frame becomes a second (20x as long as the original video). I think this will still work for me, though, because my videos are only 2-5 second clips. I should find out soon.
I appreciate your input and good luck in your work.

**Comment by o5786486** [comment]
Hi @FabiTheGabi 
Can you provide the full code of the frame_wise_to_second_wise.txt?
Thank you!
